name: create-release

on:
  pull_request:
    types: [ closed ]
    branches:
    - main
    paths:
    - '**.tf'
    - 'examples/**'
    - 'test/**'

permissions:
  contents: write

run-name: create release from pr number ${{ github.event.number }}
jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:

    - name: Token generator
      uses: githubofkrishnadhas/github-access-using-githubapp@v2
      id: token-generation
      with:
        github_app_id: ${{ secrets.TOKEN_GENERATOR_APPID }}
        github_app_private_key: ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@v5
      with:
        token: ${{ steps.token-generation.outputs.token }}

    - name: create-release
      uses: devwithkrishna/devwithkrishna-create-release-action@v1.0.1
      with:
        token: ${{ steps.token-generation.outputs.token }}
        pr_number: ${{ github.event.number }}
        generate_release_notes: true
